name: ludolph-tracker
services:
  ludolph-tracker:
    image: leduck/ludolph-tracker:latest
    restart: unless-stopped
    volumes:
      - data:/app/data/
    env_file:
      - .env

volumes:
  data: